### ISSUE TITLE
Feature request--Keyboard shortcut for creating a new folder

### ISSUE THREAD

**Issue by euphonics** [pjeby/quick-explorer#1]
Would be amazing to have the ability to create a new folder via a keyboard shortcut.

Currently, the only way to create a new folder with the plug-in in the current directory is to navigate back one level, then select the folder within which you which to create the folder, then bring up the context menu (alt + enter), the navigate down to "new folder", and then finally go navigate to the folder to rename it and enter it.

Proposed modification: create a new keyboard shortcut for creating a new folder within the current directory when the Quick Explorer folder windows are open. The new folder is created within the current directory and does not require any excessive navigation or selection.

Great plug-in, thank you.

**Comment by pjeby** [comment]
I'm not quite clear on what you mean.  The keyboard sequence is:

1. Hotkey open the current folder
2. Right arrow once to make a subfolder, or twice to make a sibling folder
3. Alt-Enter
4. Type "nf" to select new folder, then hit enter
5. Type the name of the new folder and hit enter

Or with the mouse:

1. Right click the breadcrumb whose name is the parent of the folder you want to create
2. Pick "new folder" with the mouse (or type "nf"+enter)
3. Type the name of the new folder and hit enter

I don't understand what you mean by "go navigate to the folder to rename it", since it should automatically open in the file explorer with the name selected and ready to begin typing.  Are you using another plugin that interacts with the file explorer in some way?

**Comment by euphonics** [comment]
I'm not getting the behavior you describe in step number 2 where you say "Right arrow once to make a subfolder, or twice to make a sibling folder". In that same sequence of steps, you describe steps 4 and 5 as being the actions that create the new folder, so I'm confused.

Regardless, here's what I mean... Let's say I am currently viewing /My Folder/note1.md and I want to create a new subfolder within "My folder". Given this scenario, here is what I am currently doing to create a new folder with the plug-in:

1. I press the hotkey for "browse current folder"
2. In response, the list of notes insides My Folder appear (as well as ".." to traverse down one level)
3. I select ".." and then press "left" to traverse down one level
4. In response, the list of notes now displays the root level, with "My Folder" selected
5. I press "alt + enter" to bring up the context menu
6. I type "NF" to select a new folder
7. I hit "enter" to send the command 
8. finally, the new folder is created.

(Re: the comment about  "go to navigate to the folder to rename it"--nevermind about that, I see that it automatically goes to the folder name field as you said.)

That was 8 steps. What I'm proposing is the following sequence:

1. I press the hotkey for "browse current folder"
2. In response, the list of notes insides My Folder appears
3. I press a hotkey, such as "ctrl + shift + n"
4. The new folder is created

My goal is to quickly create a folder in the place that I want it without needing to reach for the mouse.

**Comment by pjeby** [comment]
Sorry, that should've been *left* arrow, not right arrow.  The left arrow takes you up a directory level *from wherever you are*, and will have the *child folder* selected.  

Whichever breadcrumb you initially open, the menu is the folder that *contains* the item named by the breadcrumb, and the item automatically selected *is* the named item.  So if you're on `Something/My Folder/My Note`, then clicking on my note opens my folder with my note selected, and clicking on My folder opens Something with My Folder selected.  The left and right arrows navigate the breadcrumbs, so if you've opened My Note, going left opens Something, with My Folder selected -- which is what you want.

So if you want to perform an operation *on* the current folder -- rather than *in* the current folder -- the very first key you should hit after opening the current folder is the left arrow.  While you are *in* the current folder, you can only perform operations on the items which are *in* the current folder, not *on* the current folder.

So, to add a folder to the current folder, you begin by going left to select the current folder (instead of its contents), then open the context menu.  If you were using the mouse, it would be just "right click My Folder and pick New Folder".  With the keyboard it's, "Browse current folder, Left arrow, alt-enter, nf enter": 6 keystrokes in all, or the same as it takes to type `mkdir` and a space at a shell prompt.  Since it's basically the same number of keystrokes for virtually *any* action you can perform on a folder within Obsidian, this doesn't seem like a huge deal to me.

If it is a big deal for you, however, there are a couple of other options you might consider.

First, the keystroke sequence is constant and timing isn't critical, so you could use a macro.

Second, you might try using folder notes -- a note with the same name as its enclosing folder -- with the Note Folder Autorename plugin.  This is actually my usual scenario for creating a new folder: I first create the note that will be its table of contents, giving it the name the folder will have.  Then I simply issue the command to convert the note to a folder, which creates the folder and moves the note inside.  Now my current folder is the new folder and any new notes I create at that point will wind up inside it.  (Using create new notes "in current folder" setting.)

Third, you might want to check out the Shell Commands plugin, which lets you define a command like `mkdir {{folder_path}}/{{clipboard}}` to register as an Obsidian command you can then assign a hotkey to.  (Doesn't look like they have an option to prompt for a variable, though: that would make it even easier.)  But it might work for what you're trying to do.
