### ISSUE TITLE
FR: Keyboard Shortcuts without pgdown/pgup/Home/End

### ISSUE THREAD

**Issue by chrisgrieser** [pjeby/quick-explorer#16]
I use the Apple keyboard, which in it's most popular version, does not have page down, page up, home and end as keys. (on Mac, you can also use cmd + arrow keys for those four keys, that does not work either)

Hence, I feel like I am missing out on half of the features. Could add alternative hotkeys for users of smaller keyboards or an option to change those hotkeys? 🙏

**Comment by pjeby** [comment]
Cmd+Up/Down for PgUp/PgDn seems doable, I'm not sure that I want to use Cmd+Left/Right, though, because there may be future uses for those.  What about Shift+Cmd+Up/Down to go to the top and bottom of a preview?  How far off Mac conventions is that?

Actually, I probably have uses for Cmd-PgUp and Cmd-PgDn, which would be really hard to do.  I'm honestly a bit stumped as to how anybody manages without a full keyboard.    ;-)

As far as remapping, I'm not entirely sure about that either.  Hm.  I guess since this is a Mac-specific issue, I could say that you have to use Ctrl for anything that'd be Ctrl on PC, i.e. Ctrl-PgDn on PC would become Ctrl-Cmd-Down on Mac.  Is that workable?  Ctrl-Home would then map as Ctrl-Cmd-Left, and Ctrl-End would be Ctrl-Cmd-Right.
