### ISSUE TITLE
[Feature Request]Search in the current folder

### ISSUE THREAD

**Issue by Andy-AO** [pjeby/quick-explorer#22]
Sometimes I want to search in the current folder, but now I can only copy the path of the file in the folder, then modify it, and then go to use `path:`, the whole process is a bit too tedious.

It would be great if explorer could have better support for searching.

**Comment by pjeby** [comment]
You mean searching the *content* of the files?

**Comment by Andy-AO** [comment]
> You mean searching the _content_ of the files?

Yes, search the contents of the entire folder, because sometimes you want to find information in this folder.

Obsidian can be implemented, but the operation is more complex.

Explorer seems that similar functions are generally provided, such as the one that comes with windows.

**Comment by Andy-AO** [comment]
At present, I use the AutoHotKey script on windows to simply realize this function. Of course, it is not stable to realize it by sending keys. Unfortunately, I don't understand JavaScript at all, otherwise I might try it.

**Comment by pjeby** [comment]
Hm.  Well, if another plugin were to add a context menu item for "search in this folder", and/or a command to search in the folder of the currently-active file, those would integrate nicely with Quick Explorer.

So, probably this is not something I'd do in Quick Explorer directly, since if there were a "search in folder" plugin that offered the capability it would be usable in other places with or without Quick Explorer.

**Comment by Andy-AO** [comment]
thanks
