### ISSUE TITLE
[Feature Request] Option to place breadcrumbs at bottom of the screen

### ISSUE THREAD

**Issue by brooksvb** [pjeby/quick-explorer#32]
I would love the option to place the breadcrumbs at the bottom of the screen, similar to this little floating status bar.

The reason being is that I would like to hide the top bar of Obsidian entirely (to maximize screen space since I am using a tiling window manager), but I would still like the breadcrumbs to be visible. 

![floating bar](https://user-images.githubusercontent.com/14019044/152874795-afa55301-2236-44c6-af01-2f56023e8c7e.png)

**Comment by pjeby** [comment]
Even if I put them in the status bar, there'd be a problem with them being on the right: cascading menus to the right does not work well in left-to-right languages.

If you just need to *see* the breadcrumbs in the status bar, you can use the Show Current File Path plugin, which was actually my original inspiration for Quick Explorer.  The first version of QE actually used the status bar and I just could not get the menus to behave in a workable fashion when they were starting at the bottom and not at the far left -- at some point I just threw up my hands and went, "okay, to the top it goes".

I have considered putting in an option to mirror the breadcrumbs to the status bar, and I might well do that still, but it will still open the menus from the top left because if you have a deep folder tree you will rue the day you opened the menus from the bottom right.  :wink:

In the meantime, Show Current File Path will put the path in the status bar for you, and you can use the keyboard commands to activate QE browsing even if the title bar is not visible.

**Comment by brooksvb** [comment]
Thank you for this suggestion! I will try it out.

Would you happen to know how I can hide this dead space on the right?

![image](https://user-images.githubusercontent.com/14019044/152917461-50f009dd-e57c-4b5a-a0d4-1e68794f7752.png)

**Comment by pjeby** [comment]
You could also talk to people on the discord, the Appearance and Appearance-Dev channels are good places to ask.  There was a discussion just the other day (though actually it might've been on plugin-dev) about making the sidebars appear only when you move the mouse over them.

**Comment by hellen-dorandt89** [comment]
This plug in is so kewl! :) Thank you devoloper
but I also really would desire this too.
Currently I have a surface pro for on the go programming and screen space is scarce. 
So I have hidden the title bar as well as the file name header for this reason.

Sadly I cannot see the breadcrumb path this plugin places at the top of the window at all. 
I do have that plug in that shows the path current files on the status bar but it would be so nice if this plug in could place its breadcrumb in its place!

Please consider having an option in the plug in settings page for this. I can live with not being able to fit the plugins UI on the window.
Thanks!

**Comment by pjeby** [comment]
As of Quick Explorer 0.1.41, the explorer will show in the status bar if you are on Obsidian 0.16 and are using the Hidden or Native frame settings (in Settings > Appearance > Advanced).  If you are on Obsidian 0.15 or less, or are using the "Obsidian frame" mode in 0.16, the explorer will remain in the title bar.

(Note: Obsidian 0.16 is still in insider beta, so if you are not an insider it may be a few weeks before you can upgrade.)
