### ISSUE TITLE
[Suggestion] Better Breadcrumb Navigation

### ISSUE THREAD

**Issue by Andrew-Do** [pjeby/quick-explorer#40]
Click folder name to navigate to folder note in breadcrumbs view. Hover to see explorer dropdown. 

Reasoning: This would speed up navigation. To open the folder note of a parent, you have to click the child and find the md which is awkward.

**Comment by Andrew-Do** [comment]
![image](https://user-images.githubusercontent.com/49578245/176326843-7522ef76-8c13-4b17-adf8-42126a3765f9.png)
When I click the Data Structures folder, with the Data Structures.md file inside of that folder, I would expect to jump to that page... 
yet this is what I see.

**Comment by pjeby** [comment]
Ah, I understand what you're saying now.  The way that it works is that clicking on an item shows that item *selected in its parent directory*.  If the Data Structures folder has a `Data Structures.md` in it, then it will appear as a page preview next to the menu (assuming you have page preview and/or Hover Editor enabled).

It works this way because it's the only way to have a consistent rule for what each dropdown does.  If it were changed to behave as you suggest, then there would be an inconsistency, in that the last dropdown would behave differently from all the others, and there would have to be an extra dropdown added to represent the root directory of the vault.

It may help to think of each dropdown as a button to "show me this item in context, selected", as that is what it does in all cases.  If you need to perform an operation *on* the item itself, you can also do so by right-clicking it instead of opening it.  That is, you can rename or move the folder, create a note in it, etc. by right-clicking the folder on the dropdown.

If what you want is to access a folder note, just click on the *child* dropdown, e.g. "string" instead of "Data Structures" in your example above.  "Data Structures.md" should be at the top of the list, right below your mouse cursor.
