### ISSUE TITLE
the vault title appears on the right

### ISSUE THREAD

**Issue by danieltomasz** [pjeby/quick-explorer#50]
but when quick explorer 0.1.35 is activated, the vault title appears on the right
Obsidian 0.15.9

![image](https://user-images.githubusercontent.com/7980381/181128309-e1360134-ed5f-449f-8350-16c83dfc02fe.png)

**Comment by pjeby** [comment]
The vault title is on the right in the screenshot you posted.  This looks exactly like what it's supposed to look like with the new Obsidian, because Obsidian 0.15 normally adds the note name to the title and puts it in the center, where it would collide with Quick Explorer, making it impractical to use with smaller windows and screens.

Is there something different you wanted it to do?

**Comment by danieltomasz** [comment]
indeed, on the right :P 

If this was the case with 0.15 I noticed this just now (I was using Insider whole time), and I have problem with Minimal, by  default the vault title is hidden, but after the latest `quick explore` update the vault name is visible again, I wasn't sure if I should address it here or as an issue for Minimal

Feel free to close this issue if this is intended behaviour

**Comment by pjeby** [comment]
I added a CSS workaround; some changes I made to make it work properly with a different theme caused it to reappear when using Minimal.  0.1.36 should fix the issue.
