### ISSUE TITLE
Arrow navigation not working

### ISSUE THREAD

**Issue by brooksvb** [pjeby/quick-explorer#7]
Unfortunately for me arrow navigation is not working properly. Left and right work, Home and End work, but Up and Down don't do anything at all; nothing gets selected, the selection doesn't move.

I would guess maybe a different plugin is interfering; there are no hotkeys bound to just the Up or Down key.

Any ideas? This seems like an awesome plugin if I could get full keyboard navigation working

**Comment by pjeby** [comment]
Have you tried disabling other plugins to see which one it is?

**Comment by brooksvb** [comment]
Actually I just discovered that the arrow navigation does seem to be working, there's just no UI feedback for the current selection. Hovering with mouse properly highlights the current selection, but arrow navigation has no highlighting. I am able to go in and out of subfolders.

**Comment by pjeby** [comment]
That's odd, Atom light works fine for me, it's one of the ones I tested.  Though to be fair it's an older version of Atom, so maybe a newer one has the problem?  I'll try reinstalling it...  no, I can see it just fine on Atom light.  Atom dark is very low contrast for the selection, though, as is 80's Neon.

What I don't get is why you're able to see it for the mouse hover but not keyboard nav, because as far as I can tell, the styling is the same for both kinds of navigation.

**Comment by brooksvb** [comment]
I tried to peek around in CSS to try a naive fix by just adding `!important`:
```
#quick-explorer .explorable.selected, #quick-explorer .explorable:hover {
      background-color: var(--interactive-accent-hover) !important;
      color: var(--text-on-accent) !important;
      opacity: 1; } 
```
 I put this in a CSS snippet and activated it, but it didn't change anything

**Comment by pjeby** [comment]
I've added an update to use a higher-contrast color pair when dark mode is active.  It won't fix 80's neon unless you have Obsidian's dark mode turned on.  It's not a great color combo on many themes, but it looks like it's pretty rare for a theme's dark mode to have a usable level of contrast for menu selection with the keyboard.

**Comment by brooksvb** [comment]
Just updated and it works perfectly! Thanks so much for the prompt attention.
