### ISSUE TITLE
File list: Clicking on a note or pressing the ENTER key DOES NOT open the note in the current tab

### ISSUE THREAD

**Issue by Randy-Astle** [pjeby/quick-explorer#72]
When I use the arrow keys to select a note in the file list, nothing happens when I:
- press enter
- Left click on it with the mouse

My expectation is that the file will open in the current tab.

This is basic functionality and scanning through the issues I noticed that at least one person stated that this worked for him. So... Perhaps something is interfering?

I have this problem in 2 of the 3 vaults that I regularly use.

Any ideas on what I might do to determine what the problem is?

Randy

**Comment by Randy-Astle** [comment]
After testing (disabling community plugins one at a time), I found that the problem is eliminated when I disable the Hover Editor.

**Comment by pjeby** [comment]
Yeah, apparently a recent Obsidian change affects when the active pane is selected -- basically what's happening is that on Obsidian 1.1.10, the pane is getting opened in the hover editor that just closed because the old active pane hasn't been re-selected.  I've added a workaround to Hover Editor 0.11.9, so updating Hover Editor should fix it for you.

**Comment by Randy-Astle** [comment]
That's actually a little amusing. 😆 

Thanks for the explanation.
