### ISSUE TITLE
What Am I Doing Wrong?

### ISSUE THREAD

**Issue by Ken9969** [pjeby/quick-explorer#86]
Hi PJ. Please take a look at my forum writing and let me know a way to go because I really like using my keyboard for going through my notes.

It is here: https://forum.obsidian.md/t/is-this-necessary/71185/3

Thanx,

Ken

**Comment by pjeby** [comment]
So, it looks like you are using those commands when you have the File Explorer focused.  They are only supposed to be used when you have a file focused.  (I never ran into this before myself, because I use Pane Relief's "Focus Lock" feature that keeps the sidebars from becoming active.)

(It would probably be reasonable, though, for me to make the file navigation commands only operate when the target file is in the focused pane -- that would keep this from happening.)

In the meantime, please note that if you have this happen to you, you can just use the "navigate back" command to get back from the note to the File Explorer.  The default hotkey for that is Alt+LeftArrow on windows, not sure what it is on Mac.  You can also use Pane Relief and focus lock to keep keyboard focus from ending up in your sidebars to begin with.

**Comment by Ken9969** [comment]
Great... Thanx...

**Comment by pjeby** [comment]
This should be fixed in 0.2.12.  Let me know if it's still an issue.  Thanks for the report!
