### ISSUE TITLE
Support more strategies for folder notes

### ISSUE THREAD

**Issue by aidenlx** [pjeby/quick-explorer#9]
This new issue is mainly opened to discuss details of folder note implementations. When the agreement to the exact implementation is established, I may then ask some other questions regarding the build system of this project and try to submit PRs when time permits and you agree to accept the PR. 

## Functional Support

Currently, [folder-note-core](https://github.com/aidenlx/folder-note-core) has been tested for a while and will soon be used by [alx-folder-note](https://github.com/aidenlx/alx-folder-note/tree/core). the API has been improved according to your demands. When you are not occupied, please do not hesitate to ask if there are more questions or needs. 

## UX Proposal

Currently, only the "inside folder, same name" strategy is used and the UI has not yet been optimized for other strategies like "outside folder" or "index name". Treating the folder notes as regular notes is fine for the current strategy, but it may cause problems for other strategies. For example, [having duplicate folders and folder notes](https://user-images.githubusercontent.com/31102694/132827506-a30fa0c4-37d9-4781-83f0-50b66594de4b.png) in the sibling menu when using the "outside folder" strategy. 

In my opinion, the different strategies are a matter of storage solution, and when it comes to UI, where folder notes really are doesn't really matter, since they are used to provide additional info for the linked folders, and the folder can be used as the only entry. So here I'm proposing several UI solutions to unify the experience for different strategies and to reduce duplication and confusion. 

### Breadcrumb

Here, I propose a solution that will keep the current breadcrumb logic, which uses an abstract file item at the end of breadcrumb to represent folder notes like so (an icon in favor of plain text may be better): 
![image](https://user-images.githubusercontent.com/31102694/132825353-8cc6c1cc-f287-4427-b592-9a05193cb6db.png).

In this solution, the actual file name is hidden from UI (should not be an issue since the name can be found in the linked folder), and the logic can remain the same as the current one: click to show siblings, right-click to show options for note, and the underlying strategy is no longer relevant: no matter where the note is, it is always shown as folder note item next to the linked folder. 

### Siblings Menu

Currently, the folder notes are placed in the file sections, treated as regular notes. I think a better solution may be  1. filter folder notes out of the file list
2. check if a folder has any folder note, and have a UI control for folder notes in/under folder item

And for folder note control in the siblings' menu, I currently have three ideas in mind: 

- insert folder note directly next to folder item (most straightforward, but taking up 2x space)
- dedicated icon for a folder with folder note, merge file-menu for note and folder (less hotkey to remember, but the menu can be lengthy)
- dedicated button & hotkey for opening file-menu of folder notes (button can be an indicator of the folder with folder note, rather complicated to implement)
  - ![image](https://user-images.githubusercontent.com/31102694/132830870-99779252-7b6c-4b54-acd3-4fefdd362de0.png)

**Comment by pjeby** [comment]
Regarding the UI, I'm going to say that hiding anything is a definite no.  Quick Explorer won't ever hide folder notes or pretend that the note and its folder are the same thing.  I'm prioritizing transparency over convenience here, to prevent confusion and support issues.  Concealing the implementation strategy of folder notes provides (at best) a minor optimization in space usage or reading time, and this isn't remotely balanced by the opportunities for confusion created by a lack of transparency.

If one were writing an app like Obsidian from the ground up with this support and insisting all plugins support this model in exactly the same way, it *might* make sense to conceal such things.  But since QE is not the only plugin or built-in facility users will use to access their notes, it does not make sense to present things in a way that will be inconsistent with their other tools, as this will lead to confusion as the representation of e.g. paths will not match.

In short, while QE will (eventually) support all three folder note strategies, I have no plans to change the UI for any of them.  (The one exception being that while outside-same notes will be previewed on folder selection, they will not be navigated to when the folder is entered, since the file is outside the folder.  While this is somewhat of a disadvantage to that approach, that approach already has so many disadvantages compared to inside-based strategies that one more will make little difference to its usefulness.)

Note that currently, entering a folder navigates immediately to its (contained) folder note, so rather than needing a new button or hotkey to perform the action described in your proposal, it currently suffices to right-arrow, backslash, or enter, alt+enter to access the context menu for a folder note.  It doesn't require learning anything new, just the use of the existing keyboard commands.

**Comment by aidenlx** [comment]
Thanks for the explanation! I understand your concern, and do you think that it’s ok to add a icon for folder notes as an indicator? In outside-same strategy, it can be helpful when there are many folders and viewing folder and the note at the same time isn’t an option. Or maybe a sort option to put them in a group at the end of list (of course, when list sorting is supported in the future)? And if it is acceptable, may I open a new issue about those?

**Comment by pjeby** [comment]
If the names of the note and folder are the same, the required uniqueness is the same, whether inside the folder or outside.  While links to the outside-same note are shorter than those to an inside-same note, links *from* an inside-same note to other files in the same folder do not require a path prefix, nor do any links to that note from others in the same folder.

Since the common uses for folder notes are to provide an overview or index to the folder contents, or to use the folder for images or other attachments. easier linking to the folder's contents is a clear win, as is the fact that Obsidian can be configured to make new notes relative to the current one.  So in most circumstances, these advantages make inside-same or inside-index the superior choices -- and adding a few tweaks to QE's UI for outside-same won't do anything to mitigate the (huge) relative disadvantages of the outside strategy.

This is why I don't see any point to adding extra features for outside-same: in practice I don't expect it to be a popular strategy, so the effort would be wasted if a feature is only useful for that strategy.

**Comment by aidenlx** [comment]
Thanks for the kind reminder of obsidian’s relative path resolve strategy, which had been my major concern of using inside-same. I will add it to the comparison table. 

Although the new note location can be monkey-patched (which I’ve added to folder-note-core in dev branch recently) and the strategy is now more usable, it’s true that not being included in folder is quite troublesome to handle sometimes (e.g. moving folder out of vault). Considering the overall effort that might be necessary to fully support this strategy in the future, I’ll be focused on adding command for batch conversion between strategies and a more detailed strategy comparison table, letting user to decide their choice.
