### ISSUE TITLE
Doesn't work with Windows Snap

### ISSUE THREAD

**Issue by notuntoward** [pjeby/quick-explorer#97]
This plugin's folder menu is very nice on Windows 11, when Obsidian is displayed without snapping (first screenshot)
![image](https://github.com/user-attachments/assets/2e73e1d5-3e4a-4fa2-81be-c22088bcc572)

However, the folder menu is unreadable when I then snap Obsidian (Windows Key + Left Arrow) and then activate quick explorer:

![image](https://github.com/user-attachments/assets/2d0c4a24-e9f9-43d5-8ef8-ca8450f2c92f)

**Comment by pjeby** [comment]
How odd.  I'm not seeing that with a snapped window on Windows 10.  What version of Obsidian are you using (actual version + installer version)?

**Comment by notuntoward** [comment]
It's Obsidian v1.6.7; installer v1.6.5

Maybe I should describe the repro steps more precisely.  With `Alt + E` mapped to `Quick Explorer: Browse vault`, I see the following:

1. full sized obsidian window
2. `Alt + E`: **no problem**
3. `Win + Left` on obsidian window: **no problem**
4. `ESC` to close the quick explorer popup
5. `Alt + E`: **the problem in my bottom screenshot**

**Comment by pjeby** [comment]
I can't repro that here, but looking more closely at your screenshot, it looks like the issue might be your over-full status bar.   If I shrink my Obsidian window such that there's not enough room for QE, then the menu ends up partly off-screen.

So I've tweaked the menu positioning code to make sure it doesn't have negative co-ordinates when bits of QE are off-screen.  I'm not really sure *why* they're offscreen instead of stacked vertically on-screen, but at least this works around the issue.  0.2.10 has the fix.

**Comment by notuntoward** [comment]
Works great now.  Thanks!
